### ISSUE TITLE
Can i make it a clickable website?

### ISSUE THREAD

**Issue by SOLMIN** [leon-good-life/coverflow-react#1]
Actually my requirement is when i click on any pic it should do some action.  Handle select is only giving me option of having alert window. 

Any help will be welcomed 
Thanks in Advance
Solmin

**Comment by leon-good-life** [comment]
Hi Solmin,
```jsx
<CoverFlow 
   imagesArr={imagesArr}
   handleSelect={(index)=>{
      // you can put here any code.
      // you can use imagesArr[index] to get the URL of the selected image.
   }}  />
```
Hope this helps,
Please let me know if you need more help,
Leon.
