### ISSUE TITLE
Stop the scrolling via trackpad

### ISSUE THREAD

**Issue by anshurathee** [leon-good-life/coverflow-react#2]
Is there a way, by which I can stop the scroll of the coverflow from trackpad. The problem is, I have added the coverflow below the header of my website. So now when I try to scroll down into the content, it scrolls the coverflow too.
Thanks

**Comment by anshurathee** [comment]
Solved it via commenting 
// var _swipeReact = require('swipe-react');
// var _swipeReact2 = _interopRequireDefault(_swipeReact);
// var _wheelReact = require('wheel-react');
// var _wheelReact2 = _interopRequireDefault(_wheelReact);
and further dependencies of these variables,
in coverflow-react>>CoverFlow>>Container>>Container.js

**Comment by leon-good-life** [comment]
Thanks Anshu
